import "@/styles/globals.css";
import { montserratFont } from "@/lang/lang";
import Footer from "@/appComponents/sections/footer";
import Navbar from "@/appComponents/sections/navbar";
import { ReactLenis } from "lenis/react";
import { Provider } from "@/components/ui/provider";

import StoreProvider from "./StoreProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ colorScheme: "dark" }} suppressHydrationWarning>
      <body className={montserratFont.className}>
        <ReactLenis root />
        <StoreProvider>
          <Navbar />
          <Provider>{children}</Provider>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
